# https://docs.github.com/en/actions/creating-actions
name:  changelog-pr
description:  Installs and runs changelog-pr

inputs:
  previoustag:
    description: 'Previous TAG to look back to'
    required: true
  token:
    description: 'Github token'
    required: true

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-actions
runs:
  # https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
  using: composite
  steps:
    -
      name: Download latest changelog-pr
      shell: bash
      run: curl -Ls https://github.com/Maahsome/changelog-pr/releases/download/$(curl -Ls https://api.github.com/repos/maahsome/changelog-pr/releases/latest | jq -r '.tag_name')/changelog-pr_linux_amd64.tar.gz | tar -zx -C ./ --strip-components=1 changelog-pr_linux_amd64/changelog-pr
    -
      name: Install changelog-pr
      shell: bash
      run: sudo install -o root -g root -m 0755 changelog-pr /usr/local/bin/changelog-pr
    -
      name: Get version
      shell: bash
      run: changelog-pr version
    -
      name: Generate ChangeLog
      shell: bash
      run: |
        changelog-pr -g github --github-token "${{ inputs.token }}" generate --path . --since-tag "${{ inputs.previoustag }}" --release-tag "v0.0.0-NEXT" -v info --file v0.0.0-NEXT.md
    -
      name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: v0.0.0-NEXT
        path: v0.0.0-NEXT.md
        retention-days: 1
